name: zeronet
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  archive: ^3.1.6
  crypto: ^3.0.1
  clipboard: ^0.1.3
  device_info: ^2.0.2
  diff_match_patch: ^0.4.1
  file_picker: ^4.6.1
  flutter_absolute_path: 
    # path: ../flutter_absolute_path
    git:
      url: https://github.com/canewsin/flutter_absolute_path.git
      # ref: android-v2
  flutter_downloader: ^1.8.0+1
  # flutter_mobx: ^1.1.0+2
  http: ^0.13.4
  # mobx: ^1.2.1+4
  get: ^4.6.5
  google_fonts: ^3.0.1
  in_app_review: ^2.0.2
  in_app_update: ^3.0.0
    # git:
    #   url: https://github.com/canewsin/flutter_in_app_update.git
  outline_material_icons: #^0.1.1-nullsafety
    git:
      url: https://github.com/ZeroNetX/outline_material_icons.git
  equatable: ^2.0.2
  time_ago_provider: ^4.1.0
  package_info_plus: 
  package_info_plus_web: 
  path_provider: ^2.0.2
  purchases_flutter: ^3.5.0
  random_string: 2.3.1
  restart_app: ^1.1.0
  share: ^2.0.4
  url_launcher: ^6.0.9
  flutter_background_service: #^0.1.5
    # path: ../flutter_background_service
    git:
      url: https://github.com/ekasetiawans/flutter_background_service
      ref: 9ad6ba3acf9952c53aa482708a4d099f9e33d98f
  flutter_webview_plugin: #^0.4.0
    # git: https://github.com/nuc134r/flutter_webview_plugin.git
    git:
      url: https://github.com/canewsin/flutter_webview_plugin
    #   ref: fullscreen-support
  # web_socket_channel: 1.1.0
  zeronet_ws: #^0.0.3
    # path: C:\Users\PramUkesh\Documents\FlutterProj\zeronet_ws
    git:
      url: https://github.com/canewsin/zeronet_ws
  internet_file: ^1.0.0+1
  bitsdojo_window: ^0.1.2
  system_tray: #^0.0.9
    git:
        url: https://github.com/antler119/system_tray.git
  msix: ^3.0.1
  flutter_inappwebview: ^5.4.1+1
    # path: ../zeronet_ws
    # git:
    #   url : https://github.com/canewsin/zeronet_ws.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  # build_runner: ^1.11.5
  # mobx_codegen: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/developers/
    - assets/icons/
    - assets/filters/